#!/usr/bin/env bash
# Oneliner:
#     wget -qO- https://raw.githubusercontent.com/jeremyll/dotfiles/master/install | sh

cd ~
mkdir -p .dotfiles
cd .dotfiles

git init
git remote add origin https://github.com/jeremyll/dotfiles.git
git pull origin master

./run.sh
