#!/usr/bin/env bash
# Oneliner:
#     wget -qO- https://raw.githubusercontent.com/jeremyll/dotfiles/master/install | sh
set -e # Stop on error
set -x # Show debug

cd ~

git clone https://github.com/jeremyll/dotfiles.git .dotfiles

cd .dotfiles

./run.sh
